name: Run Synternet Data Layer

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 23.15 CET
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: SYNTROPY_DATA_LAYER
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step to Write API_URL to a File (Temporary - Remember to Delete After)
      - name: Write API_URL to File
        run: echo "$API_URL" > api_url.txt
        env:
          API_URL: ${{ secrets.API_URL }}

      # Debugging Step: List files to verify api_url.txt is created
      - name: List Files
        run: ls -la 

      - name: Upload API_URL File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: api_url
          path: api_url.txt

      - name: Run Synternet Data Layer
        run: python SYNTERNET_DATA_LAYER.py
        continue-on-error: true
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          CSV_DIRECTORY: ${{ github.workspace }}/data

      - name: Wait and Retry if Failed
        if: failure()
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: SYNTERNET_DATA_LAYER.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          CSV_DIRECTORY: ${{ github.workspace }}/data
