name: Run Synternet Data Layer

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 23.15 CET
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: SYNTROPY_DATA_LAYER
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Debug Step to Print API_URL (Temporary - Remember to Delete After)
      - name: Debug - Print API_URL
        run: echo "API_URL is $API_URL"
        env:
          API_URL: ${{ secrets.API_URL }}

      - name: Run Synternet Data Layer
        run: python SYNTERNET_DATA_LAYER.py
        continue-on-error: true
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          CSV_DIRECTORY: ${{ github.workspace }}/data

      - name: Wait and Retry if Failed
        if: failure()
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: SYNTERNET_DATA_LAYER.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: ${{ secrets.API_URL }}
          CSV_DIRECTORY: ${{ github.workspace }}/data
